name: Deploy via Cloudflare Tunnel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Execute Remote Commands
      run: |
        ssh -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -p ${{ secrets.SSH_PORT || '22' }} \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "cd /home/mateus/user-api && \
            git fetch origin main && \
            git reset --hard origin/main && \
            sudo systemctl restart user-api"
